# Generated by Django 4.0.4 on 2022-05-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_type_alter_project_author_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author_user_id',
        ),
    ]
