# Generated by Django 4.0.4 on 2022-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_contributor_permission_alter_contributor_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("READ", "Read"), ("ALL", "All")], default="All", max_length=16
            ),
        ),
        migrations.AlterField(
            model_name="contributor",
            name="role",
            field=models.CharField(
                choices=[
                    ("AUTHOR", "Author"),
                    ("MANAGER", "Manager"),
                    ("CREATOR", "Creator"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
