# Generated by Django 4.0.4 on 2022-06-22 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_alter_contributor_permission_alter_contributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('READ', 'Read'), ('ALL', 'All')], default='ALL', max_length=16),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('MANAGER', 'Manager'), ('CREATOR', 'Creator')], default='AUTHOR', max_length=16),
        ),
    ]
